name: Test Secrets
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Project ID: ${{ secrets.EQT_PROJECT_NODE_ID }}"
      - run: echo "Status Field: ${{ secrets.STATUS_FIELD_ID }}"
      - run: echo "Seed Option: ${{ secrets.SEED_OPTION_ID }}"
