name: Test Secrets
on: [push]
permissions:
  actions: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secrets
        run: |
          echo "Project ID: ${{ secrets.EQT_PROJECT_NODE_ID }}"
          echo "Status Field: ${{ secrets.STATUS_FIELD_ID }}"
          echo "Seed Option: ${{ secrets.SEED_OPTION_ID }}"
          echo "Exploring Option: ${{ secrets.EXPLORING_OPTION_ID }}"
          echo "Validating Option: ${{ secrets.VALIDATING_OPTION_ID }}"
          echo "Community Review Option: ${{ secrets.COMMUNITY_REVIEW_OPTION_ID }}"
          echo "Initial Consensus Option: ${{ secrets.INITIAL_CONSENSUS_OPTION_ID }}"
          echo "Core Integration Option: ${{ secrets.CORE_INTEGRATION_OPTION_ID }}"
          echo "Archived Option: ${{ secrets.ARCHIVED_OPTION_ID }}"
